/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */
import type { DeleteOneResultConsumedCapacity } from './deleteOneResultConsumedCapacity';

/**
 * deleteOne操作の結果
 */
export interface DeleteOneResult {
  /** 操作が確認されたか */
  acknowledged: boolean;
  /** 削除されたドキュメントの数 */
  deletedCount: number;
  /** 削除されたドキュメントのID */
  id?: string;
  /** DynamoDB消費キャパシティ情報（集約） */
  consumedCapacity?: DeleteOneResultConsumedCapacity;
}
