/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */

/**
 * フィルタ定義

型安全なフィルタ条件を定義します。
各フィールドに対して直接値を指定するか、FilterOperatorsを使用できます。

 */
export interface Filter {
  /** AND条件 */
  $and?: Filter[];
  /** OR条件 */
  $or?: Filter[];
  [key: string]: unknown;
 }
