/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */
import type { NearOperator } from './nearOperator';

/**
 * MongoDB形式の演算子をサポートします。

サポートされる演算子:
- 比較演算子: $eq, $ne, $gt, $gte, $lt, $lte
- 配列演算子: $in, $nin
- 文字列演算子: $regex
- 地理演算子: $near（簡易形式のみ）

 */
export interface FilterOperators {
  /** 等しい（例: { age: { $eq: 25 } } または { age: 25 }） */
  $eq?: string | number | boolean;
  /** 等しくない（例: { status: { $ne: "deleted" } }） */
  $ne?: string | number | boolean;
  /** より大きい（例: { age: { $gt: 18 } }） */
  $gt?: number;
  /** 以上（例: { age: { $gte: 18 } }） */
  $gte?: number;
  /** より小さい（例: { age: { $lt: 65 } }） */
  $lt?: number;
  /** 以下（例: { age: { $lte: 65 } }） */
  $lte?: number;
  /** 配列内のいずれかに一致（例: { status: { $in: ["active", "pending"] } }） */
  $in?: (string | number | boolean)[];
  /** 配列内のいずれにも一致しない（例: { status: { $nin: ["deleted", "archived"] } }） */
  $nin?: (string | number | boolean)[];
  /** フィールドの存在チェック（例: { email: { $exists: true } }） */
  $exists?: boolean;
  /** 正規表現マッチ（例: { name: { $regex: "^John" } }） */
  $regex?: string;
  /** 近隣検索（簡易形式のみ、例: { location: { $near: { latitude: 35.6895, longitude: 139.7036, maxDistance: 5000 } } }） */
  $near?: NearOperator;
}
