/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */
import type { FindOptionsSort } from './findOptionsSort';

/**
 * 検索オプション
 */
export interface FindOptions {
  /** ソート条件（値は 1, -1, 'asc', 'desc' のいずれか） */
  sort?: FindOptionsSort;
  /**
   * 取得件数の制限
   * @minimum 1
   */
  limit?: number;
  /**
   * スキップする件数
   * @minimum 0
   */
  skip?: number;
  /** ページネーショントークン（カーソルベースのページネーション用） */
  nextToken?: string;
}
