/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */

export * from './apiErrorResponse';
export * from './apiErrorResponseError';
export * from './apiOperation';
export * from './apiRequest';
export * from './apiRequestParams';
export * from './apiSuccessResponse';
export * from './apiSuccessResponseData';
export * from './bulkOperationResult';
export * from './bulkOperationResultConsumedCapacity';
export * from './bulkOperationResultErrors';
export * from './bulkOperationResultFailedIds';
export * from './bulkOperationResultItemsItem';
export * from './bulkOperationResultSuccessIds';
export * from './collection';
export * from './consumedCapacity';
export * from './deleteManyParams';
export * from './deleteOneParams';
export * from './deleteOneResult';
export * from './deleteOneResultConsumedCapacity';
export * from './deleteResult';
export * from './deleteResultConsumedCapacity';
export * from './document';
export * from './error';
export * from './errorError';
export * from './errorErrorDetails';
export * from './executeOperation200';
export * from './executeOperation200Data';
export * from './executeOperationBody';
export * from './executeOperationBodyOp';
export * from './executeOperationBodyParams';
export * from './filter';
export * from './filterOperators';
export * from './findManyParams';
export * from './findManyReferenceParams';
export * from './findManyReferenceParamsPagination';
export * from './findManyReferenceParamsSort';
export * from './findManyReferenceParamsSortOrder';
export * from './findManyReferenceResult';
export * from './findManyReferenceResultItemsItem';
export * from './findManyReferenceResultPageInfo';
export * from './findOneParams';
export * from './findOptions';
export * from './findOptionsSort';
export * from './findParams';
export * from './findParamsPagination';
export * from './findParamsSort';
export * from './findParamsSortOrder';
export * from './findResult';
export * from './findResultConsumedCapacity';
export * from './findResultPageInfo';
export * from './getVersion200';
export * from './getVersion200Data';
export * from './insertManyParams';
export * from './insertManyParamsDataItem';
export * from './insertManyResult';
export * from './insertManyResultConsumedCapacity';
export * from './insertManyResultErrorsItem';
export * from './insertManyResultInsertedIds';
export * from './insertOneParams';
export * from './insertOneParamsData';
export * from './insertOneResult';
export * from './insertOneResultConsumedCapacity';
export * from './nearOperator';
export * from './operationError';
export * from './query';
export * from './queryFilter';
export * from './queryPagination';
export * from './querySort';
export * from './querySortOrder';
export * from './resourceName';
export * from './updateManyOptions';
export * from './updateManyParams';
export * from './updateOneOptions';
export * from './updateOneParams';
export * from './updateOneResult';
export * from './updateOneResultConsumedCapacity';
export * from './updateOperators';
export * from './updateOperatorsInc';
export * from './updateOperatorsSet';
export * from './updateOperatorsSetOnInsert';
export * from './updateResult';
export * from './updateResultConsumedCapacity';