/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */

/**
 * $near演算子（簡易形式のみサポート）

指定された地点から近い順にドキュメントを検索します。

動作:
1. シャドウレコード: 地理座標フィールドに対して、GeoHashベースのシャドウレコードが自動生成される
2. 検索精度: GeoHash精度6（±610m）から開始し、段階的に精度を下げて検索
3. 9ブロック検索: 中心ブロック + 周囲8ブロックを検索して候補を収集
4. 距離計算: Haversine公式で正確な距離を計算し、距離順にソート
5. 結果: 指定された件数（limit）まで、距離の近い順に返す

制約:
- ページネーション非対応: $near検索ではnextTokenを使用できない
- 単一フィールド: 1つのクエリで複数の地理座標フィールドを検索できない
- 他の演算子との併用: $nearと他のフィルター条件を併用できない

 */
export interface NearOperator {
  /**
   * 緯度（-90〜90）
   * @minimum -90
   * @maximum 90
   */
  latitude: number;
  /**
   * 経度（-180〜180）
   * @minimum -180
   * @maximum 180
   */
  longitude: number;
  /**
   * 最大距離（メートル）。省略時は無制限
   * @minimum 0
   */
  maxDistance?: number;
  /**
   * 最小距離（メートル）。省略時は0
   * @minimum 0
   */
  minDistance?: number;
}
