/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DynamoDB Client API
 * MongoDB-like API for DynamoDB with shadow record support for efficient querying.

This API provides a familiar MongoDB-style interface for interacting with DynamoDB,
supporting 10 operations compatible with react-admin.

**Supported Operations:**
- find: Query documents with filters
- findOne: Get a single document
- findMany: Get multiple documents by IDs
- findManyReference: Get documents by reference field
- insertOne: Create a single document
- insertMany: Create multiple documents
- updateOne: Update a single document
- updateMany: Update multiple documents
- deleteOne: Delete a single document
- deleteMany: Delete multiple documents

 * OpenAPI spec version: 1.3.34
 */
import type { UpdateOperatorsInc } from './updateOperatorsInc';
import type { UpdateOperatorsSet } from './updateOperatorsSet';
import type { UpdateOperatorsSetOnInsert } from './updateOperatorsSetOnInsert';

/**
 * 更新演算子（$プレフィックス付き - MongoDB互換）

MongoDB風の更新演算子を提供します。
すべての演算子は$プレフィックス付きで使用します（MongoDB互換）。

例:
```json
// フィールドを設定
{
  "$set": { "status": "published", "updatedAt": "2024-01-01T00:00:00Z" }
}

// フィールドを削除
{
  "$unset": ["description", "tags"]
}

// 数値をインクリメント
{
  "$inc": { "stock": -1, "viewCount": 1 }
}

// 複数の演算子を組み合わせ
{
  "$set": { "status": "published" },
  "$inc": { "viewCount": 1 },
  "$unset": ["draft"]
}
```

 */
export interface UpdateOperators {
  /** フィールドを設定 */
  $set?: UpdateOperatorsSet;
  /** upsert時のinsert専用フィールド（レコードが存在しない場合のみ適用） */
  $setOnInsert?: UpdateOperatorsSetOnInsert;
  /** フィールドを削除 */
  $unset?: string[];
  /** 数値をインクリメント（負の値でデクリメント） */
  $inc?: UpdateOperatorsInc;
}
